User requests, car requests, events requests, errorHandlers, auth
cstruchevs/Devico_Project_Server pull request #1
Opened 2022-04-29 00:13 UTC by cstruchevs

2022-04-29 17:33 UTC, VolodymyrDevico requested changes

2022-04-29 17:33 UTC, VolodymyrDevico commented on app.ts
> +    //.sync()
remove

2022-04-29 17:33 UTC, VolodymyrDevico commented on controllers/authConroller.ts
> +export const login: RequestHandler = async (req, res) => {
split on different folders

2022-04-29 17:33 UTC, VolodymyrDevico commented on controllers/authConroller.ts
> +    throw new BadRequestError("Please provide all values");
Some better error text

2022-04-29 17:33 UTC, VolodymyrDevico commented on controllers/dist/eventController.js
> +"use strict";
gitignore

2022-04-29 17:33 UTC, VolodymyrDevico commented on db/database.ts
> +const sequelize = new Sequelize('devico_project', 'root', 'semen2012', {
move to .env

2022-04-29 17:33 UTC, VolodymyrDevico commented on errors/not-found.ts
> +    public statusCude = StatusCodes.NOT_FOUND
add prettier

2022-04-29 17:33 UTC, VolodymyrDevico commented on middleware/error-handler.ts
> +  if (err.code && err.code === 11000) {
Create constants with good naming

2022-05-03 15:12 UTC, turchin-aa reviewed
Gj

2022-05-05 20:47 UTC, closed without merging